### PR TITLE
Add language selection toolbar button

### LINKED ISSUE #88: Need Language Support for SystemT Extractors in NLP-Editor
## Requirement
The language must be provided as input in the UI in the Input Document node - it should be a new property added to this node. Then that language must be used in the backend to create the compiled extractor that is executed on Run and that is exported on Export

---

## Background
In Watson Knowledge Studio's Advanced Rule Editor (now deprecated), the user would select the language option during the export. This language (same value) was needed to be specified while loading the WKS exported SystemT extractor.
Ref:
image

Opening this issue, after discussion with @laurachiticariu and @nysenthil - to have language support provided for NLP-Editor based systemT extractors.

### PR DESCRIPTION
**Pull request by marthacryan**
Fixes #88. Adds a dialog that prompts the user for the language when the "Language" toolbar button is pressed. Default value is en and the values are listed in alphabetical order. Creates `language-name.txt` in the zip file used for submission. 

Toolbar button is on the right side and displays current selection (or english by default):
image

Then shows this dialog: 
image
image

### CODE REVIEW

**Comment by laurachiticariu** [comment]
@marthacryan two questions:
1) What is the behavior when the user selects Run a second time? Do they have to specify the language a second time, or does it remember the language from the prior invocation of Run and makes that language as default? I.e., in general the user selects a language once and clicks Run many times during development. We shouldn't make the user re-select the language at each and every Run. That's why I was imagining the language as a more permanent parameter in the `Input document` node in the canvas.
2) Similar behavior would have to be implemented at `Export` time.

**Comment by nysenthil** [comment]
Hi @marthacryan 
I completed the backend code changes needed to compile and execute AQL for a user specified payload text language. I did the integration testing with the frontend code changes you made in this PR. In my testing, I used three different input documents in English, German and French. In the frontend, user has to simply select their preferred language once and then keep modifying the flow followed by performing the Run and Export tasks as many times as he/she wants. Everything works end-to-end nicely for the Run and Export tasks for a chosen language. Your frontend code changes look good.

I observed one display anomaly in the Result dialog that comes up after a successful run. It doesn't display certain non-English special characters with accent. It substitutes it with two question mark characters. For example, in my tests I used the following match phrases and it displays the results as shown below. You can see if it is fixable.

French words:
communauté --> communaut??
dévouement --> d??vouement

German words:
höflich --> h??flich
größere --> gr????ere

cc: @laurachiticariu

**Comment by laurachiticariu** [comment]
The UI should use UTF-8 encoding to display all text, including in:
- The results table
- Results highlighting panel
- Dictionary Node (the entries in the dictionary may have non ASCII characters)
We should open a new defect for this and fix it ASAP

**Comment by nysenthil** [comment]
With more testing yesterday, Martha and I confirmed that the accented German and French characters are not correctly returned by the backend to the frontend. I debugged it further today and fixed a JSON formatting problem that happened while exchanging the result JSON between two classes. Accented German and French characters now appear correctly in the result table view, result highlighting panel and in the dictionary node for manually typed match phrases as well as for the ones obtained from an uploaded German or French dictionary file.

@marthacryan Since the end-to-end testing works well now, you can plan to merge this PR. After you do that, I will create new 01_XXXX and 02_XXXX docker containers early next week.

cc: @laurachiticariu

**Comment by nysenthil** [comment]
Hi @marthacryan I used the three modified source files from your most recent commit and tested it. I can see 27 languages listed in the language selection dialog box. I chose 5 different languages (en, de, fr, es, hi) and did end-to-end testing. Everything worked as expected in the frontend and backend layers. If you can merge this to the main branch, then I will use the merged code in the main branch to create the required containers needed by our current users. Thank you.

**Comment by laurachiticariu** [comment]
@marthacryan and @JesusGuerrero could you take a look and see if you could fix the CodeQL CI failures?

**Review by laurachiticariu — APPROVED** [review]
LGTM!

**Pull request merged**
