### PR TITLE
Change export to create zip like run

### PR DESCRIPTION
**Pull request by marthacryan**
Closes https://github.com/CODAIT/nlp-editor/issues/119

This is a draft because it needs to be tested with the backend and it requires some code cleanup.

### CODE REVIEW

**Comment by nysenthil** [comment]
Hi @marthacryan I did an integration testing of your frontend code changes with the backend code changes that I did for the Export. Your new zip package is perfect and the backend extracted it, ran the flow correctly to create a result zip file (e-g: 5vVFqVim7xdH7FomxPVWQb-export.zip) in the run-aql-result directory. However, the frontend didn't pick up that export result zip file. Instead, it simply keeps spinning in the UI. Please check the code changes you made to wait for the result zip file to appear and then move it to the user's Downloads folder or timeout in case the result zip file doesn't get created in the predefined time. Thank you.

**Comment by nysenthil** [comment]
Hi @marthacryan  I tested your frontend code fix for picking up the export zip file. It works fine. However, I see that that the module name configured in the Settings configuration panel seems to be not take effect now. It used to work fine in the 0.4.0 release code. Could you please check if that is the case and provide a fix as needed. Thank you.

**Comment by nysenthil** [comment]
Hi @marthacryan You did it. "Running consecutively" as well as "Running and Exporting consecutively" multiple times worked great in my tests. I also see no more left-over temporary directories in the "nlp-editor/temp" folder after multiple runs. Thank you for your fixes.

**Comment by laurachiticariu** [comment]
Great, thanks @marthacryan ! Once the build passes, @nysenthil do approve and merge this PR.

**Comment by nysenthil** [comment]
Hi @marthacryan One more thing needs fixing before I can do a full test and merge this. When I change the module name in the Settings panel after making a few runs or after a page reload, it doesn't take effect in the concept XML file created during the next run. Please see if you can reproduce it in your environment and then fix it as needed. Thank you.

**Review by nysenthil — APPROVED** [review]

**Comment by laurachiticariu** [comment]
@marthacryan the CI/CD was failing with some error - can you fix them in a subsequent PR?

**Pull request merged**
